// import localFont from 'next/font/local'
import '@radix-ui/themes/styles.css'
import './theme-config.css'
import './globals.css'
import { Container, Theme } from '@radix-ui/themes'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import AuthProvider from './auth/Provider'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// })
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={inter.variable} lang="en">
      <body>
        <AuthProvider>
          <Theme
            accentColor="orange"
            grayColor="gray"
            radius="large"
            scaling="105%"
          >
            <NavBar />
            <main className="px-4">
              <Container>{children}</Container>
            </main>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  )
}

export const metadata = {
  title: 'Learn Meter',
  icons: {
    icon: [
      {
        rel: 'icon',
        type: 'image/x-icon',
        url: '/app/favicon/favicon.ico',
      },
      {
        rel: 'icon',
        type: 'image/png',
        sizes: '32x32',
        url: '/app/favicon/favicon-32x32.png',
      },
      {
        rel: 'icon',
        type: 'image/png',
        sizes: '16x16',
        url: '/app/favicon/favicon-16x16.png',
      },
    ],
    apple: '/app/favicon/apple-touch-icon.png',
    manifest: '/app/favicon/site.webmanifest',
  },
}
